In [14]:
import pandas as pd
df = pd.read_csv('data/Yearly_Projections_RB.csv', thousands=',')
df = df.convert_dtypes()
#df.info()
df.dtypes

Player     string
Team       string
ATT       Float64
YDS       Float64
TDS       Float64
REC       Float64
YDS.1     Float64
TDS.1     Float64
FL        Float64
FPTS      Float64
dtype: object

In [36]:
dfWeek = df.assign(RushYards = lambda x: ( x['YDS'] /17).astype(float),
                   RushTDs = lambda x: ( x['TDS'] /17), 
                   Rec = lambda x: ( x['REC'] /17),
                   PassYards = lambda x: ( x['YDS.1'] /17),
                   PassTDs = lambda x: ( x['TDS.1'] /17),
                   FL = lambda x: ( x['FL'] /17),
                   Pts =  lambda x: ( x['FPTS'] /17),
                   CalcPts = lambda x: ( x['FPTS'] /17),
                  )
dfWeek

,Player,Team,ATT,YDS,TDS,REC,YDS.1,TDS.1,FL,FPTS,RushYards,RushTDs,Rec,PassYards,PassTDs,Pts,CalcPts
0,,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1,Christian McCaffrey,CAR,297.1,1301.6,12.0,93.8,760.1,4.3,0.147059,392.4,76.564706,0.705882,5.517647,44.711765,0.252941,23.082353,23.082353
2,Dalvin Cook,MIN,317.5,1491.6,13.0,54.9,473.3,2.0,0.170588,335.1,87.741176,0.764706,3.229412,27.841176,0.117647,19.711765,19.711765
3,Alvin Kamara,NO,206.9,941.4,9.7,81.0,688.6,3.5,0.111765,319.3,55.376471,0.570588,4.764706,40.505882,0.205882,18.782353,18.782353
4,Derrick Henry,TEN,343.0,1703.2,14.2,23.8,178.6,1.1,0.158824,298.3,100.188235,0.835294,1.4,10.505882,0.064706,17.547059,17.547059
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
174,Taquan Mizzell,NYG,0.9,3.7,0.0,0.9,5.4,0.0,0.0,1.8,0.217647,0.0,0.052941,0.317647,0.0,0.105882,0.105882
175,Cullen Gillaspia,NYG,0.9,3.7,0.0,0.9,5.2,0.0,0.0,1.7,0.217647,0.0,0.052941,0.305882,0.0,0.1,0.1
176,Tony Jones Jr.,NO,0.9,0.7,0.0,0.2,0.4,0.0,0.0,0.3,0.041176,0.0,0.011765,0.023529,0.0,0.017647,0.017647
177,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
178,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>